### PR TITLE
Fix sending calibration settings

### LINKED ISSUE #180: sending the stored calibration on device bootup doesnt work

### PR DESCRIPTION
**Pull request by vdiezel**
closes #180 
branch name doesnt have the number because ticket was created afterwards

- fixes IotDataAP and sendDeviceDescriptionTrigger to send the stored calibrations to the device on bootup
- removes http middleware from triggers ( resulted in errors log on cloudwatch)
- adds test to sendDeviceDescriptionTrigger

Deployed the updated sendDeviceDescriptionTrigger to dev and prod already (was urgent)

### CODE REVIEW

File: lib/IotDataAPI.js [hunk 1]
```diff
@@ -32,9 +32,9 @@ class IotDataAPI {
     return this.execute(mqttMsg)
   }
 
-  static publishDeviceDescription(deviceId, payload) {
+  static publishStoredDeviceConfiguration(deviceId, payload) {
     const mqttMsg = {
-      topic: `deviceDescription/settings/${data.deviceId}`,
+      topic: `deviceDescription/settings/${deviceId}`,
```
Comment (vdiezel) [inline lib/IotDataAPI.js]: first bug!

File: lib/test-helpers/MockIotDataAPI.js [hunk 2]
```diff
@@ -6,6 +6,6 @@ process.env.OSPIN_AWS_REGION = 'test aws region'
 const IotDataAPI = require('IotDataAPI')
 
 IotDataAPI.publishCommand = jest.fn()
-IotDataAPI.publishDeviceDescription = jest.fn()
+IotDataAPI.publishStoredDeviceConfiguration = jest.fn()
```
Comment (vdiezel) [inline lib/test-helpers/MockIotDataAPI.js]: renamed to be less confusing as the device publishes its description, the backend responds with stored device configurations

File: services/device/src/iotTrigger/dataPointsToDb.js [hunk 3]
```diff
@@ -39,9 +33,6 @@ async function dataPointsToDb(event) {
 }
 
 exports.main = middy(dataPointsToDb)
-  .use(logUnhandledErrors())
-  .use(httpErrorHandler({ logger }))
+  .use(logUnhandledErrors({ logger }))
   .use(doNotWaitForEmptyEventLoop())
-  .use(stringifyResponseBody())
-  .use(cors())
```
Comment (vdiezel) [inline services/device/src/iotTrigger/dataPointsToDb.js]: removed http middleware

File: services/device/src/iotTrigger/trigger.js [hunk 4]
```diff
@@ -50,11 +53,11 @@ class Trigger {
         return {...calibEntry, streamId: parseInt(calibEntry.streamId)}
       })
 
-    payload = {
+    const payload = {
```
Comment (vdiezel) [inline services/device/src/iotTrigger/trigger.js]: second bug!
