### PR TITLE
fixes middleware error propagation

### LINKED ISSUE #297: When doanloading certain streams Lambda returns an Invoke error
An example is the `pressure up` stream in the heartbeat group of the FU bioreactor

Bildschirmfoto von 2020-03-18 08-12-46

### PR DESCRIPTION
**Pull request by vdiezel**
closes #297 

We had a couple of issues with our middleware: 

- after the implementation of the mongodb error middleware the order of the middlewares has been changed which caused our middleware to try to map unhandled errors to a httpError
- the mongodb error middleware broke when a mongodb error with an unknown code was thrown. I redirected those errors to be unhandled for now
- unhandled errors needed the statusCode of 500 assigned to them to be considered errors on the client side (how did I never notice this)

By investigating this issue I discovered a new one: https://github.com/ospin-web-dev/hambda/issues/299

### CODE REVIEW

File: lib/middleware/mapHandledErrorToProtocol.js [hunk 1]
```diff
@@ -8,7 +8,7 @@ const httpHandler = (handler, next) => {
   }
   handler.response.body = message
   handler.response.statusCode = statusCode
-  return next()
+  return next(handler.error)
```
Comment (vdiezel) [inline lib/middleware/mapHandledErrorToProtocol.js]: still don't now where the difference is but did it for consistency

File: lib/middleware/mapHandledErrorToProtocol.js [hunk 2]
```diff
@@ -19,12 +19,15 @@ const defaultHandler = (handler, logger, next) => {
...
-      return defaultHandler(handler, logger, next)
+  if (handler.error.handled) {
+    switch (protocol) {
+      case 'http':
+        return httpHandler(handler, next)
+      default:
+        return defaultHandler(handler, logger, next)
+    }
   }
+  return next(handler.error)
```
Comment (vdiezel) [inline lib/middleware/mapHandledErrorToProtocol.js]: unhandled error are now called last (the order used to be reverse), so I need this check here now

File: lib/middleware/mongoErrorToHandledError.js [hunk 3]
```diff
@@ -12,7 +12,7 @@ module.exports = () => ({
   onError: (handler, next) => {
     const { error } = handler
 
-    if (isMongoError(error)) {
+    if (isMongoError(error) && (error.code in MONGO_ERROR_CODE_TO_HANDLED_ERROR)) {
```
Comment (vdiezel) [inline lib/middleware/mongoErrorToHandledError.js]: considers only those errors handled which are in the map `MONGO_ERROR_CODE_HANDLED_ERROR`

File: lib/middleware/stringifyResponseBody.js [hunk 4]
```diff
@@ -26,8 +26,9 @@ const errorMiddleware = (handler, next) => {
     })
   } else {
     handler.response.body = JSON.stringify({
-      message: handler.error.message,
+      message: handler.error.message || handler.error.errmsg,
```
Comment (vdiezel) [inline lib/middleware/stringifyResponseBody.js]: error for unhandled mongo errors is on `handler.error.errmsg`

File: lib/middleware/stringifyResponseBody.js [hunk 5]
```diff
@@ -26,8 +26,9 @@ const errorMiddleware = (handler, next) => {
...
     })
+    handler.response.statusCode = 500
```
Comment (vdiezel) [inline lib/middleware/stringifyResponseBody.js]: needed this so unhandled errors are considered errors on the frontend. For some reason it's not automatically set (and it probably never was)

File: lib/middleware/stringifyResponseBody.js (hunk 4 above)
Comment (vdiezel) [reply lib/middleware/stringifyResponseBody.js]: Question: Should we provide any information for unhandled errors at all or better just return a generic message to the client? The error itself is still logged in CloudWatch, so we don't necessarily need this information on the clinet side, but it's probably more comfortable.

File: lib/middleware/mapHandledErrorToProtocol.js (hunk 1 above)
Comment (DanielSeehausen) [reply lib/middleware/mapHandledErrorToProtocol.js]: I interpreted it that calling next without passing the `handler.error` no longer bubbles up the error, and that passing it does!

File: lib/middleware/mongoErrorToHandledError.js (hunk 3 above)
Comment (DanielSeehausen) [reply lib/middleware/mongoErrorToHandledError.js]: good catch - this was an oversight on our part when implementing

File: lib/middleware/stringifyResponseBody.js (hunk 4 above)
Comment (DanielSeehausen) [reply lib/middleware/stringifyResponseBody.js]: I believe some people see this as a potential security flaw. 
I don't see an issue for us though. 
If we need to address it later maybe we could go the route of "on dev, return error message, otherwise don't"

File: lib/middleware/stringifyResponseBody.js (hunk 5 above)
Comment (DanielSeehausen) [reply lib/middleware/stringifyResponseBody.js]: I have a quick observation re: this middleware.

Now that things are becoming increasingly complex with our middleware, we should try to keep them functionally independent (and ignorant) of one another as much as possible. When conor and I were working in the middleware recently we (or at least I) found the coupling to be pretty difficult to follow and debug.

Should stringify response body have an onError action at all? It seems pretty pure as a middleware: if the response has a body, stringify it if it can be stringified.

Is the following assumption correct?: when this (or any) middleware is hit _after_ a handled error is handled in a middleware, it is no longer an error, and it shouldn't be hitting its onError in the case of a handled error.

That seems right and the original intent, but looking at this middleware's implementation it doesn't look like that is what is happening.

File: lib/middleware/mapHandledErrorToProtocol.js (hunk 2 above)
Comment (DanielSeehausen) [reply lib/middleware/mapHandledErrorToProtocol.js]: I left a comment in the middlewares mentioning this after conor and I worked on it. Was very strange and I couldn't identify why!

File: lib/middleware/stringifyResponseBody.js (hunk 4 above)
Comment (vdiezel) [reply lib/middleware/stringifyResponseBody.js]: splitting up by environment is a good idea!

File: lib/middleware/stringifyResponseBody.js (hunk 5 above)
Comment (vdiezel) [reply lib/middleware/stringifyResponseBody.js]: that is definitely a valid point. I just can't remeber if the error handler in the stringify body middleware was done because of a rush, lack of understanding or because I had too...
I create a new ticket for this one.

Comment (vdiezel) [reply lib/middleware/stringifyResponseBody.js]: https://github.com/ospin-web-dev/hambda/issues/301

File: lib/middleware/mapHandledErrorToProtocol.js (hunk 1 above)
Comment (vdiezel) [reply lib/middleware/mapHandledErrorToProtocol.js]: I tried that and it doesn't seem to be the case. It seems more like it checks if there is an error present on the handler, and if so, call the onError middleware. At least behaviour never seemed to be altered when I switch between `next()` and `next(handler.error)`

Comment (ConorTighe1995) [reply lib/middleware/mapHandledErrorToProtocol.js]: It looks kinda like ExpressJs in the sense if you want the callback to proceed you just call next() but passing a parameter will throw whats passed eg. next('throw this'). I've only seen this with ExpressJs but it must be a callback pattern for JS libs.
