### PR TITLE
Fix : close all mongodb opened handles to fix jest test

### LINKED ISSUE #140: fix open handlers in test suite

### PR DESCRIPTION
**Pull request by O-Susanoo**
closes #140

### CODE REVIEW

File: lib/mongodb-lib.js [hunk 1]
```diff
@@ -1,10 +1,11 @@
 const MongoClient = require('mongodb').MongoClient;
-
+let conn = null;
```
Comment (DanielSeehausen) [inline lib/mongodb-lib.js]: don't forget a space or double space between deps and code please!

File: lib/mongodb-lib.js [hunk 2]
```diff
@@ -27,3 +28,6 @@ async function getProdDB() {
 exports.db = async function db() {
   return await process.env.NODE_ENV === 'test' ? getTestDB() : getProdDB()
 };
+exports.conn = ()=>{
+  return conn
+};
```
Comment (DanielSeehausen) [inline lib/mongodb-lib.js]: might need to change your newline setting on that computer as well

Comment (O-Susanoo) [reply lib/mongodb-lib.js]: Thank you for the update , i'm now on eslint theoretically i should not repeat those mistakes
