### PR TITLE
Format client error stack trace

### LINKED ISSUE #233: format client error stacktrace in hambda

### PR DESCRIPTION
**Pull request by O-Susanoo**
closes #233

### CODE REVIEW

File: services/utils/src/logger/logger.js [hunk 1]
```diff
@@ -4,13 +4,24 @@ const errorToSlackString = require('./serializers/errorToSlackString')
 
 class Logger {
```
Comment (DanielSeehausen) [inline services/utils/src/logger/logger.js]: this snuck by first time, but just as a heads up - if a file is exporting a capital Class, it should be named the same 
`logger` --> `Logger`

File: services/utils/test/logger/logClientError.test.js [hunk 2]
```diff
@@ -78,7 +85,7 @@ describe('Logger Class', () => {
       )
       expect(fetch).toHaveBeenCalledWith(
         expect.anything(),
-        expect.objectContaining({ body: expect.stringContaining(errorObject.stackTrace) })
+        expect.objectContaining({ body: expect.stringContaining(errorObject.fileName) })
```
Comment (DanielSeehausen) [inline services/utils/test/logger/logClientError.test.js]: since we are testing for one of the new values, we should probably be checking for all of the new values

there may be a lot of duplication in these expects here!
