### PR TITLE
fix devicelogs endpoints

### LINKED ISSUE #122: devicelogs api throws errors and causes the webapp to crash in `log` tab

### PR DESCRIPTION
**Pull request by vdiezel**
fixes device log bug by importing the success function from the correct library and adjust passing down data using the new `dank` pattern by @DanielSeehausen 
closes #122

### CODE REVIEW

File: services/device/src/log/create.js [hunk 1]
```diff
@@ -13,24 +13,22 @@ const {
   jsonBodyParser
 } = require('middy/middlewares')
 
-const { success } = require('success-lib')
+const { success } = require('response-lib')
```
Comment (DanielSeehausen) [inline services/device/src/log/create.js]: 👀 my fault!
